### ISSUE TITLE
JOSS Review: Reproduce figures from paper

### ISSUE THREAD

**Issue by emilljungberg** [imr-framework/OCTOPUS#3]
I ran the Cartesian demo (`numsim_cartesian.py`) and Non-Cartesian demo (`numsim_spiral.py`) from the examples folder to generate the figure in the manuscript but I seems like the figures I get are not the same as in the manuscript. (ignore the difference in the labels, that's just a viewer/font-size issue)

The **Cartesian result** appear right-left flipped compared to the manuscript
![cartesian_results](https://user-images.githubusercontent.com/3906827/91837008-df395400-ec4b-11ea-8bde-640e8358a344.png)

and the **Spiral results** appear to have much less distortions than in the manuscript
![spiral_results](https://user-images.githubusercontent.com/3906827/91837080-f6784180-ec4b-11ea-98d2-783cf40f35e9.png)

Related to this, why is the frequency offset range different for the Cartesian and spiral simulations? +/- 4800 Hz seems like a very large off-resonance range. B0 maps would typically span the range of about +/- 100Hz, making the spiral simulation seems to be more in the realistic range.

Re: [openjournals/joss-reviews/#2578](https://github.com/openjournals/joss-reviews/issues/2578)

**Comment by Mmj94** [comment]
1. You're right, it is not possible to exactly reproduce the figures in the manuscript. This is because the field map simulation used for both the cartesian and non-cartesian demos is random. However, I believe I saved the field maps for the figures shown in the manuscript (There is some commented code related to this in both scripts titled "For reproducibility").  Let me know if you would like to exactly reproduce those figures and I'll upload the files to the repository. 

2. Regarding your second point: The off-resonance offset is very large for the cartesian case just because we are exploring reconstruction techniques in highly inhomogeneous fields for a different project. Apart from that, the cartesian trajectory ultra-short readout time makes it less prone to off-resonance artifacts, therefore, needing a much larger frequency range compared to the spiral case to show equivalent image distortion.

Please let me know if these comments are helpful and if I can close this issue.

**Comment by emilljungberg** [comment]
Ah right I see I didn't realise that. But looking through the code now that makes sense. It could be an idea to use a seeded random number generator in your example script which would ensure that your samples are pseudo random, such that you get the same random numbers every time. It would allow the user to make sure they have everything working correctly if they can reproduce the same images as in the paper.

Example usage in `numpy` discussed in this thread for instance:
https://stackoverflow.com/questions/22994423/difference-between-np-random-seed-and-np-random-randomstate

**Comment by Mmj94** [comment]
Good point!
Please see if 8711fea6ba29c0256ef2e3b6fb802fa2266be41e would work.

**Comment by emilljungberg** [comment]
Would you be able to regenerate the figures on your end so that I can reproduce them with this fix? Thanks!

**Comment by Mmj94** [comment]
Please see the new figure in the paper. You should be able to reproduce it now.
See 9ebbc28df555261d5495893cdd3fca04d838f368.

**Comment by emilljungberg** [comment]
Thanks! Yes, I was able to reproduce the figures.
